// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class ImMsg;
@class ImMsgBuilder;



@interface MsgRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define ImMsg_i @"i"
#define ImMsg_s @"s"
#define ImMsg_r @"r"
#define ImMsg_t @"t"
#define ImMsg_d @"d"
#define ImMsg_c @"c"
#define ImMsg_a @"a"
#define ImMsg_time @"time"
#define ImMsg_mark @"mark"
#define ImMsg_subm @"subm"
#define ImMsg_mid @"mid"
@interface ImMsg : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTime_:1;
  BOOL hasMid_:1;
  BOOL hasI_:1;
  BOOL hasS_:1;
  BOOL hasD_:1;
  BOOL hasA_:1;
  BOOL hasMark_:1;
  BOOL hasSubm_:1;
  BOOL hasC_:1;
  BOOL hasT_:1;
  SInt64 time;
  SInt64 mid;
  NSString* i;
  NSString* s;
  NSString* d;
  NSString* a;
  NSString* mark;
  NSString* subm;
  NSData* c;
  UInt32 t;
  NSMutableArray * rArray;
}
- (BOOL) hasI;
- (BOOL) hasS;
- (BOOL) hasT;
- (BOOL) hasD;
- (BOOL) hasC;
- (BOOL) hasA;
- (BOOL) hasTime;
- (BOOL) hasMark;
- (BOOL) hasSubm;
- (BOOL) hasMid;
@property (readonly, strong) NSString* i;
@property (readonly, strong) NSString* s;
@property (readonly, strong) NSArray * r;
@property (readonly) UInt32 t;
@property (readonly, strong) NSString* d;
@property (readonly, strong) NSData* c;
@property (readonly, strong) NSString* a;
@property (readonly) SInt64 time;
@property (readonly, strong) NSString* mark;
@property (readonly, strong) NSString* subm;
@property (readonly) SInt64 mid;
- (NSString*)rAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ImMsgBuilder*) builder;
+ (ImMsgBuilder*) builder;
+ (ImMsgBuilder*) builderWithPrototype:(ImMsg*) prototype;
- (ImMsgBuilder*) toBuilder;

+ (ImMsg*) parseFromData:(NSData*) data;
+ (ImMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImMsg*) parseFromInputStream:(NSInputStream*) input;
+ (ImMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ImMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ImMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ImMsgBuilder : PBGeneratedMessageBuilder {
@private
  ImMsg* resultImMsg;
}

- (ImMsg*) defaultInstance;

- (ImMsgBuilder*) clear;
- (ImMsgBuilder*) clone;

- (ImMsg*) build;
- (ImMsg*) buildPartial;

- (ImMsgBuilder*) mergeFrom:(ImMsg*) other;
- (ImMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ImMsgBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasI;
- (NSString*) i;
- (ImMsgBuilder*) setI:(NSString*) value;
- (ImMsgBuilder*) clearI;

- (BOOL) hasS;
- (NSString*) s;
- (ImMsgBuilder*) setS:(NSString*) value;
- (ImMsgBuilder*) clearS;

- (NSMutableArray *)r;
- (NSString*)rAtIndex:(NSUInteger)index;
- (ImMsgBuilder *)addR:(NSString*)value;
- (ImMsgBuilder *)setRArray:(NSArray *)array;
- (ImMsgBuilder *)clearR;

- (BOOL) hasT;
- (UInt32) t;
- (ImMsgBuilder*) setT:(UInt32) value;
- (ImMsgBuilder*) clearT;

- (BOOL) hasD;
- (NSString*) d;
- (ImMsgBuilder*) setD:(NSString*) value;
- (ImMsgBuilder*) clearD;

- (BOOL) hasC;
- (NSData*) c;
- (ImMsgBuilder*) setC:(NSData*) value;
- (ImMsgBuilder*) clearC;

- (BOOL) hasA;
- (NSString*) a;
- (ImMsgBuilder*) setA:(NSString*) value;
- (ImMsgBuilder*) clearA;

- (BOOL) hasTime;
- (SInt64) time;
- (ImMsgBuilder*) setTime:(SInt64) value;
- (ImMsgBuilder*) clearTime;

- (BOOL) hasMark;
- (NSString*) mark;
- (ImMsgBuilder*) setMark:(NSString*) value;
- (ImMsgBuilder*) clearMark;

- (BOOL) hasSubm;
- (NSString*) subm;
- (ImMsgBuilder*) setSubm:(NSString*) value;
- (ImMsgBuilder*) clearSubm;

- (BOOL) hasMid;
- (SInt64) mid;
- (ImMsgBuilder*) setMid:(SInt64) value;
- (ImMsgBuilder*) clearMid;
@end


// @@protoc_insertion_point(global_scope)
